name: Update Mdo Statistics

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-stats:
    runs-on: ubuntu-latest
    env:
      GIST_ID: ${{ secrets.GIST_ID }}
      GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Run update script
        run: python your_script.py
